server:
  port: 8000
spring:
  datasource:
    #url: jdbc:mysql://106.15.251.229:3306/hcf?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:postgresql://192.168.12.219:5432/postgres?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: postgres
    username: postgres
  elasticsearch:
    rest:
      uris: http://192.168.12.219:9200,http://192.168.12.218:9200,http://192.168.12.217:9200
      read-timeout: 60s
  data:
    mongodb:
      #uri: mongodb://192.168.12.217:27200,192.168.12.218:27200,192.168.12.219:27200/vesionbook?retryWrites=false
      uri: mongodb://106.15.251.229:27017/hcf?retryWrites=false

logging:
  level:
    root: warn
  config: src/main/resources/logback.xml


fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 106.15.251.229:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5



xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-executor-hcf
      address:
      ip:
      port: 9797
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30